#!/bin/bash -

# Run this script to view a man page without installing it.
# `nroff -man' can show simple text files too, similar to
# `fmt file | less'. Not good for viewing source code, though.

manpage="$1"

if [ $# -eq 0 ]; then
  echo "Usage: ${0##*/} manfile.1"
  exit 1
fi

if [ ! -f $manpage ]; then
  echo The file \'${manpage}\' cannot be found
  exit 1
fi

case $manpage in
  *.[Gg][Zz])  man ./$manpage ;;
     *)  /usr/bin/nroff -man $manpage | less
esac
